### ISSUE TITLE
Modernizer Master server problems

### ISSUE THREAD

**Issue by Spawnsite** [haekb/nolf1-modernizer#50] opened 2022-02-26 00:58 UTC
The master server seems to have a issue discarding shut down servers, this makes it sluggish when listing servers ingame.
By now there are 52 listed servers in the server feed when 3/4 of these are shut down and gone.

**Comment by haekb** [comment] 2022-02-28 16:48
Thanks for the report. Caused by unprompted php version upgrade. It should be fixed now.

**Closed as completed by haekb** 2022-02-28 16:48 UTC
Labels: bug
